### ISSUE TITLE
`run` / `wait` can get stuck when using Next.js with App Router 

### ISSUE THREAD

**Issue by mattt** [replicate/replicate-javascript#136]
At yesterday's hackathon, a participant shared that predictions created and polled for completion using `run` would hang indefinitely, despite the Replicate dashboard showing that prediction as finishing minutes earlier.

After debugging by adding a `console.log` statement in the `progress` callback function, we determined that this behavior was caused by the extensions to `fetch` made by Next.js when using App Router [^1]. From ["Data Fetching, Caching, and Revalidating"](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating) in the Next.js docs:

> Next.js extends the native [fetch Web API](https://developer.mozilla.org/docs/Web/API/Fetch_API) to allow you to configure the [caching](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#caching-data) and [revalidating](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#revalidating-data) behavior for each fetch request on the server. React extends fetch to automatically [memoize](https://nextjs.org/docs/app/building-your-application/data-fetching/patterns#fetching-data-where-its-needed) fetch requests while rendering a React component tree.
> ...
> By default, **Next.js automatically caches the returned values of fetch in the [Data Cache](https://nextjs.org/docs/app/building-your-application/caching#data-cache)** on the server. This means that the data can be fetched at build time or request time, cached, and reused on each data request.

Because the initial `GET /v1/predictions/{id}` response was cached, subsequent requests polling for status returned the same response, which had the initial `"starting"` status.

Our workaround involved setting `replicate.fetch` to a wrapped function that specified a [`cache: no-store` fetch option](https://nextjs.org/docs/app/building-your-application/caching#fetch-optionscache). But it's unclear whether there's a better way to get the desired behavior.

We should either document or add a workaround to make this work correctly in Next.js.

[^1]: `fetch` when using [Pages Router](https://nextjs.org/docs/pages/building-your-application), like in the ["Build a website with Next.js"](https://replicate.com/docs/get-started/nextjs) sample project, works as expected.

**Comment by mirko314** [comment]
Hey,
I also just ran into this, and it took me quite some time to debug and come to the conclusion that some "magical" caching must be the culprit.

Would you mind to share your workaround code?

With App Router and Vercel getting even more traction, this definatly should be addressed!

**Comment by mattt** [comment]
@mirko314 Thanks for sharing. That's a helpful data point.

Here's what I remember the code to be. Please give this a try and let me know if that works for you:

```js
replicate = new Replicate({/*...*/})
replicate.fetch = (url, options) => {
  return fetch(url, { ...options, cache: "no-store" });
};
```

**Comment by Autometrique** [comment]
@mattt @mirko314 
Hi!
Thanks for this very helpful comment.
I ran into this too. I'm fairly new to next.js with the app router and having a hard time trying to make it work.
Maybe would you have a more complete exemple to share, showing how you managed to make it work?

I'm trying to use it within a replicate create/wait structure (which is equivalent to run/wait)

That would be fantastic :-)

I agree this should be addressed. We won't be the only ones trying to use replicate on the new next.js app router.

Thanks!

**Comment by Pondorasti** [comment]
Just ran into the same issue and this fixed it for me too. Thanks for the post @mattt, probably saved me hours of troubleshooting 🙌

https://github.com/replicate/replicate-javascript/issues/136#issuecomment-1728053102

**Comment by Autometrique** [comment]
@mattt Would it be possible to update the documentation with a more detailed explanation on how to use replicate-javascript on next.js recent versions? 😃

**Comment by CoreOrca** [comment]
I am also having this issue. I have tried the no Store solutions... I was going to post this as a new issue, but I think it is really part of this issue. 

I have a production deployment I am testing on Vercel that uses Replicate APIs. The code in my page.tsx and route.ts and [id]/route.ts is based on your code in the “getting-started-nextjs-typescript” template. Everything worked really well in development, but now that it is running on vercel, it gets hung up on the “starting” status update even though the prediction has been completed (when I look in the replicate dashboard I see the image and completed status). The prediction image just won’t load, it just stays stuck on “starting”, occasionally makes it to “processing” (once or twice I DID have the image load but it was minutes later).

I have looked into other causes, there was some excessive middleware calling due to my supabase auth, that seems to have abated with an adjustment to the matcher. Also tried a vercel deployment of an older version of this project with different auth and database and still had the issue with prediction image not loading. 

I also just tried rewriting my api to “replicate.run” format instead of replicate.create but still have status stuck /images not loading issue…

I just gave it one more try with the exact code from your “getting-started-nextjs-typescript” template and same issue.

I am stumped.
Please help me if possible. Thank you!

[code for replicate issue 3-1-24.txt](https://github.com/replicate/replicate-javascript/files/14465473/code.for.replicate.issue.3-1-24.txt)

**Comment by zeke** [comment]
I've opened a couple PRs to help prevent further confusion about this:

- https://github.com/replicate/replicate-javascript/pull/264
- https://github.com/replicate/getting-started-nextjs/pull/104

**Comment by wuyasong** [comment]
> 您无需改变复制`fetch`行为，就可以选择`noStore`退出组件的缓存。
> 
> ```js
> import Replicate from 'replicate';
> import { unstable_noStore as noStore } from 'next/cache';
> 
> let replicate = new Replicate(...);
>  
> export default async function Component() {
>   noStore();
>   let prediction = await replicate.predictions.create(...)
>   ...
> }
> ```
> 
> API：[https：//nextjs.org/docs/app/api-reference/functions/unstable_noStore](https://nextjs.org/docs/app/api-reference/functions/unstable_noStore)


This Great, I was stuck with this issue for a day, and after reading this issue, it was finally fixed
