### ISSUE TITLE
Allow full model URL as argument to `replicate.run()`

### ISSUE THREAD

**Issue by zeke** [replicate/replicate-javascript#27]
An idea from @mattt on https://www.loom.com/share/a0f9287c0bfe4b80bf403f21e30cc2da

<img width="417" alt="Screenshot 2023-03-24 at 2 05 20 PM" src="https://user-images.githubusercontent.com/2289/227641239-fbf2f55d-8ba7-4b05-9cba-8ea131eeed16.png">

**Comment by mattt** [comment]
Thanks for translating this into an issue, @zeke 😄 

Thinking more about the implementation, I want this to feel more like expanding shorthand than supporting multiple different formats. That is, rather than saying: 

> `replicate.run` takes one of the following argument formats..."

I want the explanation to be more like 

> `replicate.run` takes a model identifier. When you pass `"salesforce/blip:2e1dddc"` that's just shorthand for `"[https://replicate.com/]salesforce/blip:2e1dddc8621f72155f24cf2e0adbde548458d3cab9f00c0139eea840d0ac4746"`.

To make that happen, we should make the new, canonical route for a model version on the site to be `replicate.com/{owner}/{name}:{version}`. I'll create a tracking issue for that and get to work.

**Comment by SangVoM** [comment]
it is a good idea. Please start it

**Comment by zeke** [comment]
@SangVoM we may not get to this immediately, but you're welcome to open a pull request if you want to add support for it!

**Comment by SangVoM** [comment]
@zeke Can I request one model?

**Comment by zeke** [comment]
@SangVoM what do you mean?

**Comment by SangVoM** [comment]
@zeke  I want you to support some checkpoints in Civitai Okay?

**Comment by mattt** [comment]
Closing as not currently planned.
